### model
model_name_or_path: /map-vepfs/yubo/models/Qwen2.5-32B
#trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: webinstruct_2-4k_r1_cft_data_0223
template: qwen
cutoff_len: 8192
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output_models_0223/qwen2.5-32b_webinstruct_2-4k_r1_cft_data_0223_exp_0
logging_steps: 1
save_steps: 2
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
#val_size: 0.000001
#per_device_eval_batch_size: 1
#eval_strategy: steps
#eval_steps: 400
