### model
model_name_or_path: /gpfs/public/research/xy/yubowang/models/Qwen2.5-Math-7B
trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: CriticCoT_correct_only_data_1231
template: qwen
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output_models/qwen2.5-math-7B_correct-only_1231-0109
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
#val_size: 0.000001
#per_device_eval_batch_size: 1
#eval_strategy: steps
#eval_steps: 400
