### model
model_name_or_path: /mnt/hwfile/opendatalab/yubo/models/Qwen2.5-32B
#trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: false
finetuning_type: full
# deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: deepmath_qwen_32b_distill_cft_0424
template: qwen
cutoff_len: 16384
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output_models_0425/deepmath_qwen_32b_distill_cft_0424
logging_steps: 1
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
sequence_parallel_size: 8
per_device_train_batch_size: 1
gradient_accumulation_steps: 64
learning_rate: 5.0e-6
num_train_epochs: 1.0
lr_scheduler_type: constant_with_warmup
warmup_ratio: 0.1
bf16: true
#bf16: false
#fp16: false
ddp_timeout: 180000000

### eval
#val_size: 0.000001
#per_device_eval_batch_size: 1
#eval_strategy: steps
#eval_steps: 400
